apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-mount-efs-volume
  namespace: pod-mount-efs-volume-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
