apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-mount-s3-bucket
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      # bucketName: pod-mount-s3-bucket-533267434488
      bucketName: xxxxx
